apps/iam/urls.py
# from . import api
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from .swagger import get_swagger_view
from . import views


api_v1 = [
    path('authentication/', include('authentication.urls.api_urls', namespace='api-auth')),
    path('common/', include('common.urls.api_urls', namespace='api-common')),
    path('account/', include('account.urls.api_urls', namespace='api-account')),
    path('access/', include('access.urls.api_urls', namespace='api-access')),
    path('orgs/', include('organization.urls.api_urls', namespace='api-orgs')),
    path('audits/', include('audits.urls.api_urls', namespace='api-audits')),
    path('assets/', include('assets.urls.api_urls', namespace='api-assets')),
]


app_view_patterns = [
    path('auth/', include('authentication.urls.views_urls', namespace='auth')),
    path('audits/', include('audits.urls.views_urls', namespace='audits')),
    path('assets/', include('assets.urls.views_urls', namespace='assets')),
    path('account/', include('account.urls.views_urls', namespace='account')),
    path('credentials/', include('access.urls.views_urls', namespace='credentials')),
]


js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)


urlpatterns = [
    # path('', api.IndexAPI.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('v1/', include(api_v1)),
    path('i18n/<str:lang>/', views.I18NView.as_view(), name='i18n-switch'),
    # External apps url
    path('captcha/', include('captcha.urls')),
]

urlpatterns += app_view_patterns
urlpatterns += js_i18n_patterns

if settings.DEBUG:
    urlpatterns += [
        re_path('swagger(?P<format>.json|.yaml)',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        # path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

apps/audits/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: models.py
@ide: PyCharm
@time: 2020/5/25 13:00
@desc:
"""
import uuid
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from organization.utils import current_org
from organization.mixins.models import OrgModelMixin


__all__ = [
    'OperateLog', 'PasswordLog', 'LoginLog',
]


class OperateLog(OrgModelMixin):
    ACTION_CREATE = 'create'
    ACTION_UPDATE = 'update'
    ACTION_DELETE = 'delete'
    ACTION_CHOICES = (
        (ACTION_CREATE, _("Create")),
        (ACTION_UPDATE, _("Update")),
        (ACTION_DELETE, _("Delete"))
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.CharField(max_length=128, verbose_name=_('User'))
    action = models.CharField(max_length=16, choices=ACTION_CHOICES, verbose_name=_("Action"))
    resource_type = models.CharField(max_length=64, verbose_name=_("Resource Type"))
    resource = models.CharField(max_length=128, verbose_name=_("Resource"))
    remote_addr = models.CharField(max_length=15, verbose_name=_("Remote addr"), blank=True, null=True)
    datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "<{}> {} <{}>".format(self.user, self.action, self.resource)


class PasswordLog(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.CharField(max_length=128, verbose_name=_('User'))
    change_by = models.CharField(max_length=128, verbose_name=_("Change by"))
    remote_addr = models.CharField(max_length=15, verbose_name=_("Remote addr"), blank=True, null=True)
    datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} change {}'s password".format(self.change_by, self.user)


class LoginLog(models.Model):
    LOGIN_TYPE_CHOICE = (
        ('W', 'Web'),
        ('T', 'Terminal'),
    )

    MFA_DISABLED = 0
    MFA_ENABLED = 1
    MFA_UNKNOWN = 2

    MFA_CHOICE = (
        (MFA_DISABLED, _('Disabled')),
        (MFA_ENABLED, _('Enabled')),
        (MFA_UNKNOWN, _('-')),
    )

    STATUS_CHOICE = (
        (True, _('Success')),
        (False, _('Failed'))
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    username = models.CharField(max_length=128, verbose_name=_('Username'))
    type = models.CharField(choices=LOGIN_TYPE_CHOICE, max_length=2, verbose_name=_('Login type'))
    ip = models.GenericIPAddressField(verbose_name=_('Login ip'))
    city = models.CharField(max_length=254, blank=True, null=True, verbose_name=_('Login city'))
    user_agent = models.CharField(max_length=254, blank=True, null=True, verbose_name=_('User agent'))
    mfa = models.SmallIntegerField(default=MFA_UNKNOWN, choices=MFA_CHOICE, verbose_name=_('MFA'))
    reason = models.CharField(default='', max_length=128, blank=True, verbose_name=_('Reason'))
    status = models.BooleanField(max_length=2, default=True, choices=STATUS_CHOICE, verbose_name=_('Status'))
    datetime = models.DateTimeField(default=timezone.now, verbose_name=_('Date login'))

    @classmethod
    def get_login_logs(cls, date_from=None, date_to=None, user=None, keyword=None):
        login_logs = cls.objects.all()
        if date_from and date_to:
            date_from = "{} {}".format(date_from, '00:00:00')
            date_to = "{} {}".format(date_to, '23:59:59')
            login_logs = login_logs.filter(
                datetime__gte=date_from, datetime__lte=date_to
            )
        if user:
            login_logs = login_logs.filter(username=user)
        if keyword:
            login_logs = login_logs.filter(
                Q(ip__contains=keyword) |
                Q(city__contains=keyword) |
                Q(username__contains=keyword)
            )
        if not current_org.is_root():
            username_list = current_org.get_org_members().values_list('username', flat=True)
            login_logs = login_logs.filter(username__in=username_list)
        return login_logs

    @property
    def reason_display(self):
        from authentication.errors import reason_choices, old_reason_choices
        reason = reason_choices.get(self.reason)
        if reason:
            return reason
        reason = old_reason_choices.get(self.reason, self.reason)
        return reason

    class Meta:
        ordering = ['-datetime', 'username']

apps/audits/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: views.py
@ide: PyCharm
@time: 2020/5/25 13:13
@desc:
"""
import json
import uuid
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.utils.translation import ugettext as _
from django.db.models import Q

from audits.utils import get_excel_response, write_content_to_excel
from common.mixins import DatetimeSearchMixin
from common.permissions import (
    PermissionsMixin, IsOrgAdmin, IsValidUser, IsOrgAuditor
)
from organization.utils import current_org
# from ops.views import CommandExecutionListView as UserCommandExecutionListView
from .models import OperateLog, PasswordLog, LoginLog
from .utils import get_resource_type_list


class OperateLogListView(PermissionsMixin, DatetimeSearchMixin, ListView):
    model = OperateLog
    template_name = 'audit/operate_log_list.html'
    paginate_by = settings.DISPLAY_PER_PAGE
    user = action = resource_type = ''
    date_from = date_to = None
    actions_dict = dict(OperateLog.ACTION_CHOICES)
    permission_classes = [IsOrgAdmin | IsOrgAuditor]

    def get_queryset(self):
        self.queryset = super().get_queryset()
        self.user = self.request.GET.get('user')
        self.action = self.request.GET.get('action')
        self.resource_type = self.request.GET.get('resource_type')

        filter_kwargs = dict()
        filter_kwargs['datetime__gt'] = self.date_from
        filter_kwargs['datetime__lt'] = self.date_to
        if self.user:
            filter_kwargs['user'] = self.user
        if self.action:
            filter_kwargs['action'] = self.action
        if self.resource_type:
            filter_kwargs['resource_type'] = self.resource_type
        if filter_kwargs:
            self.queryset = self.queryset.filter(**filter_kwargs).order_by('-datetime')
        return self.queryset

    def get_context_data(self, **kwargs):
        context = {
            'user_list': current_org.get_org_members(),
            'actions': self.actions_dict,
            'resource_type_list': get_resource_type_list(),
            'date_from': self.date_from,
            'date_to': self.date_to,
            'user': self.user,
            'resource_type': self.resource_type,
            "app": _("Audits"),
            "action": _("Operate log"),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class PasswordLogList(PermissionsMixin, DatetimeSearchMixin, ListView):
    model = PasswordLog
    template_name = 'audit/password_log_list.html'
    paginate_by = settings.DISPLAY_PER_PAGE
    user = ''
    date_from = date_to = None
    permission_classes = [IsOrgAdmin | IsOrgAuditor]

    def get_queryset(self):
        users = current_org.get_org_members()
        self.queryset = super().get_queryset().filter(
            user__in=[user.__str__() for user in users]
        )
        self.user = self.request.GET.get('user')

        filter_kwargs = dict()
        filter_kwargs['datetime__gt'] = self.date_from
        filter_kwargs['datetime__lt'] = self.date_to
        if self.user:
            filter_kwargs['user'] = self.user
        if filter_kwargs:
            self.queryset = self.queryset.filter(**filter_kwargs).order_by('-datetime')
        return self.queryset

    def get_context_data(self, **kwargs):
        context = {
            'user_list': current_org.get_org_members(),
            'date_from': self.date_from,
            'date_to': self.date_to,
            'user': self.user,
            "app": _("Audits"),
            "action": _("Password change log"),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class LoginLogListView(PermissionsMixin, DatetimeSearchMixin, ListView):
    template_name = 'audit/login_log_list.html'
    model = LoginLog
    paginate_by = settings.DISPLAY_PER_PAGE
    user = keyword = ""
    date_to = date_from = None
    permission_classes = [IsOrgAdmin | IsOrgAuditor]

    @staticmethod
    def get_org_members():
        users = current_org.get_org_members().values_list('username', flat=True)
        return users

    def get_queryset(self):
        if current_org.is_default():
            queryset = super().get_queryset()
        else:
            users = self.get_org_members()
            queryset = super().get_queryset().filter(username__in=users)

        self.user = self.request.GET.get('user', '')
        self.keyword = self.request.GET.get("keyword", '')

        queryset = queryset.filter(
            datetime__gt=self.date_from, datetime__lt=self.date_to
        )
        if self.user:
            queryset = queryset.filter(username=self.user)
        if self.keyword:
            queryset = queryset.filter(
                Q(ip__contains=self.keyword) |
                Q(city__contains=self.keyword) |
                Q(username__contains=self.keyword)
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Audits'),
            'action': _('Login log'),
            'date_from': self.date_from,
            'date_to': self.date_to,
            'user': self.user,
            'keyword': self.keyword,
            'user_list': self.get_org_members(),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


# class CommandExecutionListView(UserCommandExecutionListView):
#     user_id = None
#
#     @staticmethod
#     def get_user_list():
#         users = current_org.get_org_members(exclude=('Auditor',))
#         return users
#
#     def get_queryset(self):
#         queryset = self._get_queryset()
#         self.user_id = self.request.GET.get('user')
#         org_users = self.get_user_list()
#         if self.user_id:
#             queryset = queryset.filter(user=self.user_id)
#         else:
#             queryset = queryset.filter(user__in=org_users)
#         return queryset
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context.update({
#             'app': _('Audits'),
#             'action': _('Command execution log'),
#             'date_from': self.date_from,
#             'date_to': self.date_to,
#             'user_list': self.get_user_list(),
#             'keyword': self.keyword,
#             'user_id': self.user_id,
#         })
#         return context


@method_decorator(csrf_exempt, name='dispatch')
class LoginLogExportView(PermissionsMixin, View):
    permission_classes = [IsValidUser]

    def get(self, request):
        fields = [
            field for field in LoginLog._meta.fields
        ]
        filename = 'login-logs-{}.csv'.format(
            timezone.localtime(timezone.now()).strftime('%Y-%m-%d_%H-%M-%S')
        )
        excel_response = get_excel_response(filename)
        header = [field.verbose_name for field in fields]
        login_logs = cache.get(self.request.GET.get('spm', ''), [])

        response = write_content_to_excel(
            excel_response, login_logs=login_logs, header=header, fields=fields
        )
        return response

    def post(self, request):
        try:
            date_from = json.loads(self.request.body).get('date_from', [])
            date_to = json.loads(self.request.body).get('date_to', [])
            user = json.loads(self.request.body).get('user', [])
            keyword = json.loads(self.request.body).get('keyword', [])

            login_logs = LoginLog.get_login_logs(
                date_from=date_from, date_to=date_to, user=user,
                keyword=keyword,
            )
        except ValueError:
            return HttpResponse('Json object not valid', status=400)
        spm = uuid.uuid4().hex
        cache.set(spm, login_logs, 300)
        url = reverse('audits:login-log-export') + '?spm=%s' % spm
        return JsonResponse({'redirect': url})

apps/audits/templates/audit/login_log_list.html
{% extends '_base_list.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}

{% block head_title %}{{ action }}{% endblock %}

{% block bread_crumbs %}
    <li class="breadcrumb-item active">{{ action }}</li>
{% endblock %}

<div class="table-responsive m-t-40">
    {% block table_container %}
        <table class="table m-t-30 table-hover contact-list" id="login_log_table">
            <thead>
            <tr>
                <th class="text-center">{% trans 'ID' %}</th>
                <th class="text-center">{% trans 'Username' %}</th>
                <th class="text-center">{% trans 'Type' %}</th>
                <th class="text-center">{% trans 'UA' %}</th>
                <th class="text-center">{% trans 'IP' %}</th>
                <th class="text-center">{% trans 'City' %}</th>
                <th class="text-center">{% trans 'MFA' %}</th>
                <th class="text-center">{% trans 'Reason' %}</th>
                <th class="text-center">{% trans 'Status' %}</th>
                <th class="text-center">{% trans 'Date' %}</th>
            </tr>
            <thead>
            <div class="m-t-40">
                <form id="search_form" method="get" action="" class="pull-right form-inline">
                    <div class="form-group row">
                        <div class="col-md-4">
                            <div class="input-daterange input-group" id="datepicker">
                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                <input type="text" id="id_date_from" class="form-control" name="date_from" value="{{ date_from|date:'Y-m-d' }}">
                                <span class="input-group-addon">to</span>
                                <input type="text" id="id_date_to" class="form-control" name="date_to" value="{{ date_to|date:'Y-m-d' }}">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <select class="select2 form-control custom-select select2-hidden-accessible" name="user">
                                <option>{% trans 'Select user' %}</option>
                                {% for u in user_list %}
                                    <option value="{{ u }}" {% if u == user %} selected {% endif %}>{{ u }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-4">
                            <div class="controls">
                                <div class="input-group">
                                    <input type="text" id="search" name="keyword" class="form-control" placeholder="{% trans 'Search' %}" value="{{ keyword }}" aria-invalid="false">
                                    <span class="input-group-btn">
                                        <button id='search_btn' class="btn btn-info" type="submit">Go!</button>
                                    </span>
                                </div>
                                <div class="help-block"></div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <tbody>
            {% for login_log in object_list %}
                <tr class="gradeX">
                    <td class="text-center">{{ forloop.counter }}</td>
                    <td class="text-center">{{ login_log.username }}</td>
                    <td class="text-center">{{ login_log.get_type_display }}</td>
                    <td class="text-center">
                    <span href="javascript:void(0);" data-toggle="tooltips"
                          title="{{ login_log.user_agent }}">{{ login_log.user_agent | truncatechars:10 }}</span>
                    </td>
                    <td class="text-center">{{ login_log.ip }}</td>
                    <td class="text-center">{{ login_log.city }}</td>
                    <td class="text-center">{{ login_log.get_mfa_display }}</td>
                    <td class="text-center">{{ login_log.reason_display }}</td>
                    <td class="text-center">{{ login_log.get_status_display }}</td>
                    <td class="text-center">{{ login_log.datetime }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div id="actions" class="" style="margin-top: -20px">
            <div class="input-group">
                <select class="form-control m-b" style="width: auto" id="slct_bulk_update">
                    <option value="export">{% trans 'Export' %}</option>
                </select>
                <div class="input-group-btn pull-left" style="padding-left: 5px;">
                    <button id='btn_bulk_update' style="height: 32px;" class="btn btn-sm btn-primary btn_export">
                        {% trans 'Submit' %}
                    </button>
                </div>
            </div>
        </div>

    {% endblock %}
</div>

{% block custom_foot_js %}
    <link href="{% static '/assets/plugins/select2/css/select2.min.css.bak.css' %}" rel="stylesheet" type="text/css" />
    <script src="{% static 'assets/plugins/select2/js/select2.full.min.js.bak.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            cloudhelper.initStaticTable('#login_log_table');
            $('#date .input-daterange').datepicker({
                format: "yyyy-mm-dd",
                todayBtn: "linked",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true

            });
            $('.select2').select2({
                dropdownAutoWidth: true,
                width: 'auto'
            });
        })
            .on('click', '.btn_export', function () {
                let date_from = $('#id_date_from').val();
                let date_to = $('#id_date_to').val();
                let user = $('.select2 option:selected').val();
                let keyword = $('#search').val();
                $.ajax({
                    url: "{% url "audits:login-log-export" %}",
                    method: 'POST',
                    data: JSON.stringify({
                        'date_from': date_from,
                        'date_to': date_to,
                        'user': user,
                        'keyword': keyword
                    }),
                    dataType: "json",
                    success: function (data) {
                        window.open(data.redirect)
                    },
                    error: function () {
                        toastr.error('Export failed');
                    }
                })
            })
    </script>
{% endblock %}

apps/audits/templates/audit/operate_log_list.html
{% extends '_base_list.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}

apps/audits/templates/audit/password_log_list.html
{% extends '_base_list.html' %}
{% load i18n %}
{% load static %}
{% load common_tags %}