apps/iam/urls.py
# from . import api
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from .swagger import get_swagger_view
from . import views


api_v1 = [
    path('authentication/', include('authentication.urls.api_urls', namespace='api-auth')),
    path('common/', include('common.urls.api_urls', namespace='api-common')),
    path('account/', include('account.urls.api_urls', namespace='api-account')),
    path('access/', include('access.urls.api_urls', namespace='api-access')),
    path('orgs/', include('organization.urls.api_urls', namespace='api-orgs')),
    path('audits/', include('audits.urls.api_urls', namespace='api-audits')),
    path('assets/', include('assets.urls.api_urls', namespace='api-assets')),
]


app_view_patterns = [
    path('auth/', include('authentication.urls.views_urls', namespace='auth')),
    path('audits/', include('audits.urls.views_urls', namespace='audits')),
    path('assets/', include('assets.urls.views_urls', namespace='assets')),
    path('account/', include('account.urls.views_urls', namespace='account')),
    path('credentials/', include('access.urls.views_urls', namespace='credentials')),
]


js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)


urlpatterns = [
    # path('', api.IndexAPI.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('v1/', include(api_v1)),
    path('i18n/<str:lang>/', views.I18NView.as_view(), name='i18n-switch'),
    # External apps url
    path('captcha/', include('captcha.urls')),
]

urlpatterns += app_view_patterns
urlpatterns += js_i18n_patterns

if settings.DEBUG:
    urlpatterns += [
        re_path('swagger(?P<format>.json|.yaml)',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        # path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

apps/account/models/group.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: group.py
@ide: PyCharm
@time: 2019/12/19 15:52
@desc:
"""
import uuid

from django.db import models
from django.utils.translation import ugettext_lazy as _

from organization.mixins.models import OrgModelMixin

__all__ = ['UserGroup']


class UserGroup(OrgModelMixin):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    name = models.CharField(max_length=128, verbose_name=_('Name'))
    comment = models.TextField(blank=True, verbose_name=_('Comment'))
    date_created = models.DateTimeField(auto_now_add=True, null=True, verbose_name=_('Date created'))
    created_by = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def users_display(self):
        return ' '.join([user.username for user in self.users.all()])

    class Meta:
        ordering = ['name']
        unique_together = [('org_id', 'name'), ]
        verbose_name = _("User group")

    @classmethod
    def initial(cls):
        default_group = cls.objects.filter(name='Default')
        if not default_group:
            group = cls(name='Default', created_by='System', comment='Default user group')
            group.save()
        else:
            group = default_group[0]
        return group

apps/account/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: forms.py
@ide: PyCharm
@time: 2020/4/17 16:07
@desc:
"""
from django import forms
from django.utils.translation import gettext_lazy as _
from django.conf import settings

from common.utils import validate_ssh_public_key
from organization.mixins.forms import OrgModelForm
from .models import User, UserGroup
from .utils import check_password_rules, get_current_org_members


class UserCheckPasswordForm(forms.Form):
    username = forms.CharField(label=_('Username'), max_length=100)
    password = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput,
        max_length=128, strip=False
    )


class UserCheckOtpCodeForm(forms.Form):
    otp_code = forms.CharField(label=_('MFA code'), max_length=6)


def get_source_choices():
    choices_all = dict(User.SOURCE_CHOICES)
    choices = [
        (User.SOURCE_LOCAL, choices_all[User.SOURCE_LOCAL]),
    ]
    if settings.AUTH_LDAP:
        choices.append((User.SOURCE_LDAP, choices_all[User.SOURCE_LDAP]))
    if settings.AUTH_OPENID:
        choices.append((User.SOURCE_OPENID, choices_all[User.SOURCE_OPENID]))
    if settings.AUTH_RADIUS:
        choices.append((User.SOURCE_RADIUS, choices_all[User.SOURCE_RADIUS]))
    return choices


class UserCreateUpdateFormMixin(OrgModelForm):
    role_choices = ((i, n) for i, n in User.ROLE_CHOICES if i != User.ROLE_APP)
    password = forms.CharField(
        label=_('Password'), widget=forms.PasswordInput,
        max_length=128, strip=False, required=False,
    )
    role = forms.ChoiceField(
        choices=role_choices, required=True,
        initial=User.ROLE_USER, label=_("Role")
    )
    source = forms.ChoiceField(
        choices=get_source_choices, required=True,
        initial=User.SOURCE_LOCAL, label=_("Source")
    )
    public_key = forms.CharField(
        label=_('ssh public key'), max_length=5000, required=False,
        widget=forms.Textarea(attrs={'placeholder': _('ssh-rsa AAAA...')}),
        help_text=_('Paste user id_rsa.pub here.')
    )

    class Meta:
        model = User
        fields = [
            'username', 'name', 'email', 'groups', 'wechat',
            'source', 'phone', 'role', 'date_expired',
            'comment', 'mfa_level'
        ]
        widgets = {
            'mfa_level': forms.RadioSelect(),
            'groups': forms.SelectMultiple(
                attrs={
                    'class': 'select2',
                    'data-placeholder': _('Join user groups')
                }
            )
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(UserCreateUpdateFormMixin, self).__init__(*args, **kwargs)

        roles = []
        # Super admin user
        if self.request.user.is_superuser:
            roles.append((User.ROLE_ADMIN, dict(User.ROLE_CHOICES).get(User.ROLE_ADMIN)))
            roles.append((User.ROLE_USER, dict(User.ROLE_CHOICES).get(User.ROLE_USER)))
            roles.append((User.ROLE_AUDITOR, dict(User.ROLE_CHOICES).get(User.ROLE_AUDITOR)))

        # Org admin user
        else:
            user = kwargs.get('instance')
            # Update
            if user:
                role = kwargs.get('instance').role
                roles.append((role, dict(User.ROLE_CHOICES).get(role)))
            # Create
            else:
                roles.append((User.ROLE_USER, dict(User.ROLE_CHOICES).get(User.ROLE_USER)))

        field = self.fields['role']
        field.choices = set(roles)

    def clean_public_key(self):
        public_key = self.cleaned_data['public_key']
        if not public_key:
            return public_key
        if self.instance.public_key and public_key == self.instance.public_key:
            msg = _('Public key should not be the same as your old one.')
            raise forms.ValidationError(msg)

        if not validate_ssh_public_key(public_key):
            raise forms.ValidationError(_('Not a valid ssh public key'))
        return public_key

    def clean_password(self):
        password_strategy = self.data.get('password_strategy')
        # 创建-不设置密码
        if password_strategy == '0':
            return
        password = self.data.get('password')
        # 更新-密码为空
        if password_strategy is None and not password:
            return
        if not check_password_rules(password):
            msg = _('* Your password does not meet the requirements')
            raise forms.ValidationError(msg)
        return password

    def save(self, commit=True):
        password = self.cleaned_data.get('password')
        mfa_level = self.cleaned_data.get('mfa_level')
        public_key = self.cleaned_data.get('public_key')
        user = super().save(commit=commit)
        if password:
            user.reset_password(password)
        if mfa_level:
            user.mfa_level = mfa_level
            user.save()
        if public_key:
            user.public_key = public_key
            user.save()
        return user


class UserCreateForm(UserCreateUpdateFormMixin):
    EMAIL_SET_PASSWORD = _('Generate a reset connection and send it to the user')
    CUSTOM_PASSWORD = _('Set password')
    PASSWORD_STRATEGY_CHOICES = (
        (0, EMAIL_SET_PASSWORD),
        (1, CUSTOM_PASSWORD)
    )
    password_strategy = forms.ChoiceField(
        choices=PASSWORD_STRATEGY_CHOICES, required=True, initial=0,
        widget=forms.RadioSelect(), label=_('Password strategy')
    )


class UserUpdateForm(UserCreateUpdateFormMixin):
    pass


class UserProfileForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label=_("Username"))
    name = forms.CharField(label=_("Name"))
    email = forms.CharField(disabled=True)

    class Meta:
        model = User
        fields = [
            'username', 'name', 'email',
            'wechat', 'phone',
        ]


UserProfileForm.verbose_name = _("Profile")


class UserMFAForm(forms.ModelForm):

    mfa_description = _(
        'When enabled, '
        'you will enter the MFA binding process the next time you log in. '
        'you can also directly bind in '
        '"profile -> setting -> MFA Settings"!')

    class Meta:
        model = User
        fields = ['mfa_level']
        widgets = {'mfa_level': forms.RadioSelect()}
        help_texts = {
            'mfa_level': _(
                '* Enable MFA authentication to make the account more secure.'
            )
        }


UserMFAForm.verbose_name = _("MFA")


class UserFirstLoginFinishForm(forms.Form):
    finish_description = _(
        'In order to protect you and your company, '
        'please keep your account, '
        'password and key sensitive information properly. '
        '(for example: setting complex password, enabling MFA authentication)'
    )


UserFirstLoginFinishForm.verbose_name = _("Finish")


class UserPasswordForm(forms.Form):
    old_password = forms.CharField(
        max_length=128, widget=forms.PasswordInput,
        label=_("Old password")
    )
    new_password = forms.CharField(
        min_length=5, max_length=128,
        widget=forms.PasswordInput,
        label=_("New password")
    )
    confirm_password = forms.CharField(
        min_length=5, max_length=128,
        widget=forms.PasswordInput,
        label=_("Confirm password")
    )

    def __init__(self, *args, **kwargs):
        self.instance = kwargs.pop('instance')
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if not self.instance.check_password(old_password):
            raise forms.ValidationError(_('Old password error'))
        return old_password

    def clean_confirm_password(self):
        new_password = self.cleaned_data['new_password']
        confirm_password = self.cleaned_data['confirm_password']

        if new_password != confirm_password:
            raise forms.ValidationError(_('Password does not match'))
        return confirm_password

    def save(self):
        password = self.cleaned_data['new_password']
        self.instance.reset_password(new_password=password)
        return self.instance


class UserPublicKeyForm(forms.Form):
    pubkey_description = _('Automatically configure and download the SSH key')
    public_key = forms.CharField(
        label=_('ssh public key'), max_length=5000, required=False,
        widget=forms.Textarea(attrs={'placeholder': _('ssh-rsa AAAA...')}),
        help_text=_('Paste your id_rsa.pub here.')
    )

    def __init__(self, *args, **kwargs):
        if 'instance' in kwargs:
            self.instance = kwargs.pop('instance')
        else:
            self.instance = None
        super().__init__(*args, **kwargs)

    def clean_public_key(self):
        public_key = self.cleaned_data['public_key']
        if self.instance.public_key and public_key == self.instance.public_key:
            msg = _('Public key should not be the same as your old one.')
            raise forms.ValidationError(msg)

        if public_key and not validate_ssh_public_key(public_key):
            raise forms.ValidationError(_('Not a valid ssh public key'))
        return public_key

    def save(self):
        public_key = self.cleaned_data['public_key']
        if public_key:
            self.instance.public_key = public_key
            self.instance.save()
        return self.instance


UserPublicKeyForm.verbose_name = _("Public key")


class UserBulkUpdateForm(OrgModelForm):
    users = forms.ModelMultipleChoiceField(
        required=True,
        label=_('Select users'),
        queryset=User.objects.none(),
        widget=forms.SelectMultiple(
            attrs={
                'class': 'users-select2',
                'data-placeholder': _('Select users')
            }
        )
    )

    def __init__(self, *args, **kwargs):

apps/account/views/group.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: group.py
@ide: PyCharm
@time: 2020/4/20 19:00
@desc:
"""
from django.utils.translation import ugettext as _
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.messages.views import SuccessMessageMixin

from common.utils import get_logger
from common.const import create_success_msg, update_success_msg
from common.permissions import PermissionsMixin, IsOrgAdmin
from organization.utils import current_org
from ..models import UserGroup
from .. import forms

__all__ = ['UserGroupListView', 'UserGroupCreateView', 'UserGroupDetailView',
           'UserGroupUpdateView', 'UserGroupGrantedAssetView']
logger = get_logger(__name__)


class UserGroupListView(PermissionsMixin, TemplateView):
    template_name = 'group/user_group_list.html'
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('User group list')
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupCreateView(PermissionsMixin, SuccessMessageMixin, CreateView):
    model = UserGroup
    form_class = forms.UserGroupForm
    template_name = 'group/user_group_create_update.html'
    success_url = reverse_lazy('users:user-group-list')
    success_message = create_success_msg
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('Create user group'),
            'type': 'create'
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupUpdateView(PermissionsMixin, SuccessMessageMixin, UpdateView):
    model = UserGroup
    form_class = forms.UserGroupForm
    template_name = 'group/user_group_create_update.html'
    success_url = reverse_lazy('users:user-group-list')
    success_message = update_success_msg
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('Update user group'),
            'type': 'update'

        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupDetailView(PermissionsMixin, DetailView):
    model = UserGroup
    context_object_name = 'user_group'
    template_name = 'group/user_group_detail.html'
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        users = current_org.get_org_members(exclude=('Auditor',)).exclude(
            groups=self.object)
        context = {
            'app': _('Users'),
            'action': _('User group detail'),
            'users': users,
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class UserGroupGrantedAssetView(PermissionsMixin, DetailView):
    model = UserGroup
    template_name = 'group/user_group_granted_asset.html'
    context_object_name = 'user_group'
    object = None
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Users'),
            'action': _('User group granted asset'),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

apps/account/templates/users/_select_user_modal.html
{% extends '_modal.html' %}
{% load i18n %}
{% block modal_class %}modal-lg{% endblock %}
{% block modal_id %}select_user_modal{% endblock %}
{% block modal_title%}{% trans "Please Select User" %}{% endblock %}
{% block modal_body %}
<table class="table table-striped table-bordered table-hover " id="select_user_table" >
    <thead>
        <tr>
            <th class="text-center">
                <div class="checkbox checkbox-default">
                    <input id="" type="checkbox" class="ipt_check_all">
                    <label></label>
                </div>
            </th>
            <th class="text-center">{% trans 'Name' %}</th>
            <th class="text-center">{% trans 'Username' %}</th>
            <th class="text-center">{% trans 'Role' %}</th>
            <th class="text-center">{% trans 'User group' %}</th>
            <th class="text-center">{% trans 'Asset num' %}</th>
            <th class="text-center">{% trans 'Active' %}</th>
        </tr>
    </thead>
</table>
{% endblock %}
{% block modal_confirm_id %}btn_select_user{% endblock %}

apps/account/templates/users/_user_update_pk_modal.html
{% extends '_modal.html' %}
{% load i18n %}
{% block modal_id %}user_update_pk_modal{% endblock %}
{% block modal_title%}{% trans "Update User SSH Public Key" %}{% endblock %}
{% block modal_body %}
<textarea id="txt_pk" class="form-control" cols="30" rows="10" placeholder="ssh-rsa AAAAB3NzaC1yc2EAA....."></textarea>
{% endblock %}
{% block modal_confirm_id %}btn_user_update_pk{% endblock %}

apps/account/templates/users/user_create.html
{% extends 'users/_user.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block password %}
    <div class="form-group row">
        <label class="col-md-3 col-form-label" for="{{ form.password_strategy.id_for_label }}">{{ form.password_strategy.label }}</label>
        <div class="col-md-9">
            <div class="radio radio-success" id="id_password_strategy">
                <div class="form-check">
                    <input checked="" class="with-gap radio-col-blue" id="id_password_strategy_0" name="password_strategy" required="" title="" type="radio" value="0">
                    <label class="form-check-label" for="id_password_strategy_0">{% trans "Generate a reset connection and send it to the user" %}</label>
                </div>
                <div class="form-check">
                    <input class="with-gap radio-col-blue" id="id_password_strategy_1" name="password_strategy" required="" title="" type="radio" value="1">
                    <label class="form-check-label" for="id_password_strategy_1">{% trans "Set password" %}</label>
                </div>
            </div>
        </div>
    </div>

    {% bootstrap_field form.password layout="horizontal" %}

    <div id="container">
        <div class="popover fade bottom in" role="tooltip" id="popover777" style=" display: none; width:260px;">
            <div class="arrow" style="left: 50%;"></div>
            <h3 class="popover-title" style="display: none;"></h3>
            <h4>{% trans 'Your password must satisfy' %}</h4>
            <div id="id_password_rules" style="color: #908a8a; margin-left:20px; font-size:15px;"></div>
            <h4 style="margin-top: 10px;">{% trans 'Password strength' %}</h4>
            <div id="id_progress"></div>
            <div class="popover-content"></div>
        </div>
    </div>


<script>
function passwordCheck() {
    if ($('#id_password').length !== 1) {
        return
    }
    let el = $('#id_password_rules'),
        idPassword = $('#id_password'),
        idPopover = $('#popover777'),
        container = $('#container'),
        progress = $('#id_progress'),
        password_check_rules = {{ password_check_rules|safe }},
        minLength = 6,
        top = idPassword.offset().top - $('.navbar').outerHeight(true) - $('.page-heading').outerHeight(true) -77 + 34,
        left = 377,
        i18n_fallback = {
            "wordMinLength": "{% trans 'Your password is too short' %}",
            "wordMaxLength": "{% trans 'Your password is too long' %}",
            "wordInvalidChar": "{% trans 'Your password contains an invalid character' %}",
            "wordNotEmail": "{% trans 'Do not use your email as your password' %}",
            "wordSimilarToUsername": "{% trans 'Your password cannot contain your username' %}",
            "wordTwoCharacterClasses": "{% trans 'Use different character classes' %}",
            "wordRepetitions": "{% trans 'Too many repetitions' %}",
            "wordSequences": "{% trans 'Your password contains sequences' %}",
            "errorList": "{% trans 'Errors:' %}",
            "veryWeak": "{% trans 'Very weak' %}",
            "weak": "{% trans 'Weak' %}",
            "normal": "{% trans 'Normal' %}",
            "medium": "{% trans 'Medium' %}",
            "strong": "{% trans 'Strong' %}",
            "veryStrong": "{% trans 'Very strong' %}"
        };

    $.each(password_check_rules, function (idx, rules) {
        if(rules.key === 'id_security_password_min_length'){
            minLength = rules.value
        }
    });

    // 初始化popover弹窗
    initPopover(container, progress, idPassword, el, password_check_rules, i18n_fallback);

    // 监听事件
    idPassword.on('focus', function () {
        idPopover.css('top', top);
        idPopover.css('left', left);
        idPopover.css('display', 'block');
    });
    idPassword.on('blur', function () {
        idPopover.css('display', 'none');
    });
    idPassword.on('keyup', function(){
        let password = idPassword.val();
        checkPasswordRules(password, minLength);
    });
}
// 顯示/隱藏 HTML 元素
let password_strategy_radio_input = 'input[type=radio][name=password_strategy]';
function passwordStrategyFieldsDisplay(){
    let val = $('input:radio[name="password_strategy"]:checked').val();
    if(val === '0'){
        $('#id_password').parents('.form-group').addClass('d-none')
    }else {
        $('#id_password').parents('.form-group').removeClass('d-none')
    }
}

$(document).ready(function () {
    passwordCheck();
    passwordStrategyFieldsDisplay()

}).on('change', password_strategy_radio_input, function(){
        passwordStrategyFieldsDisplay()
})
.on("submit", "form", function (evt) {
    evt.preventDefault();
    let the_url = '{% url 'api-account:user-list' %}';
    let redirect_to = '{% url "account:user-list" %}';
    let method = "POST";
    let form = $("form");
    let data = form.serializeObject();
    objectAttrsIsList(data, ['groups']);
    objectAttrsIsDatetime(data,['date_expired']);
    let props = {
        url: the_url,
        data: data,
        method: method,
        form: form,
        redirect_to: redirect_to
     };
    formSubmit(props);
})
</script>
{% endblock %}

apps/account/templates/users/user_granted_asset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

apps/account/templates/users/user_password_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load i18n %}

{% block head_title %}{% trans action %}{% endblock %}

{% block bread_crumbs %}
    <li class="breadcrumb-item active">{% trans action %}</li>
{% endblock %}

{% block custom_head_css_js %}
    <link href="{% static "assets/plugins/cropper/cropper.min.css" %}" rel="stylesheet">
    <link href="{% static "assets/plugins/sweetalert/sweetalert.css" %}" rel="stylesheet">
    <script src="{% static "assets/plugins/sweetalert/sweetalert.min.js" %}"></script>
    <script type="text/javascript" src="{% static 'js/pwstrength-bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-12 col-xlg-9 col-md-7">
                <div class="card">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs profile-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:user-profile-update' %}" role="tab">{% trans 'Profile' %}</a>
                        </li>
                        {% if request.user.can_update_password %}
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'account:user-password-update' %}" role="tab">{% trans 'Password' %}</a>
                            </li>
                        {% endif %}
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <!--second tab-->
                        <div class="tab-pane active" id="password" role="tabpanel">
                            <div class="card-body">
                                <form method="post" class="form-horizontal form-material" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% bootstrap_field form.old_password layout="horizontal" %}
                                    {% bootstrap_field form.new_password layout="horizontal" %}
                                    {#  密码popover  #}
                                    <div id="container">
                                        <div class="popover fade bottom in" role="tooltip" id="popover777" style=" display: none; width:260px;">
                                            <div class="arrow" style="left: 50%;"></div>
                                            <h3 class="popover-title" style="display: none;"></h3>
                                            <h4>{% trans 'Your password must satisfy' %}</h4><div id="id_password_rules" style="color: #908a8a; margin-left:20px; font-size:15px;"></div>
                                            <h4 style="margin-top: 10px;">{% trans 'Password strength' %}</h4><div id="id_progress"></div>
                                            <div class="popover-content"></div>
                                        </div>
                                    </div>
                                    {% bootstrap_field form.confirm_password layout="horizontal" %}

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <button id="submit_button" type="submit" class="btn btn-outline-success">{% trans 'Submit' %}</button>
                                            <button type="reset" class="btn btn-outline-warning">{% trans 'Reset' %}</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Column -->
        </div>
        <!-- Row -->
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
    </div>
{% endblock %}

{% block custom_foot_js %}
    <script src="{% static 'assets/plugins/cropper/cropper.min.js' %}"></script>
    <script>
        $(document).ready(function () {

            let el = $('#id_password_rules'),
                idPassword = $('#id_new_password'),
                idPopover = $('#popover777'),
                container = $('#container'),
                progress = $('#id_progress'),
                password_check_rules = {{ password_check_rules|safe }},
                minLength = 6,
                top = idPassword.offset().top - $('.navbar').outerHeight(true) - $('.page-heading').outerHeight(true) - 10 + 34,
                left = 377,
                i18n_fallback = {
                    "veryWeak": "{% trans 'Very weak' %}",
                    "weak": "{% trans 'Weak' %}",
                    "normal": "{% trans 'Normal' %}",
                    "medium": "{% trans 'Medium' %}",
                    "strong": "{% trans 'Strong' %}",
                    "veryStrong": "{% trans 'Very strong' %}"
                };

            jQuery.each(password_check_rules, function (idx, rules) {
                if(rules.key === 'id_security_password_min_length'){
                    minLength = rules.value
                }
            });

            // 初始化popover
            initPopover(container, progress, idPassword, el, password_check_rules, i18n_fallback);

            // 监听事件
            idPassword.on('focus', function () {
                idPopover.css('top', top);
                idPopover.css('left', left);
                idPopover.css('display', 'block');
            });
            idPassword.on('blur', function () {
                idPopover.css('display', 'none');
            });
            idPassword.on('keyup', function(){
                let password = idPassword.val();
                checkPasswordRules(password, minLength);
            });
        })
    </script>
{% endblock %}

apps/account/templates/users/user_pubkey_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>