apps/iam/urls.py
# from . import api
from django.conf import settings
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from .swagger import get_swagger_view
from . import views


api_v1 = [
    path('authentication/', include('authentication.urls.api_urls', namespace='api-auth')),
    path('common/', include('common.urls.api_urls', namespace='api-common')),
    path('account/', include('account.urls.api_urls', namespace='api-account')),
    path('access/', include('access.urls.api_urls', namespace='api-access')),
    path('orgs/', include('organization.urls.api_urls', namespace='api-orgs')),
    path('audits/', include('audits.urls.api_urls', namespace='api-audits')),
    path('assets/', include('assets.urls.api_urls', namespace='api-assets')),
]


app_view_patterns = [
    path('auth/', include('authentication.urls.views_urls', namespace='auth')),
    path('audits/', include('audits.urls.views_urls', namespace='audits')),
    path('assets/', include('assets.urls.views_urls', namespace='assets')),
    path('account/', include('account.urls.views_urls', namespace='account')),
    path('credentials/', include('access.urls.views_urls', namespace='credentials')),
]


js_i18n_patterns = i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
)


urlpatterns = [
    # path('', api.IndexAPI.as_view(), name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('v1/', include(api_v1)),
    path('i18n/<str:lang>/', views.I18NView.as_view(), name='i18n-switch'),
    # External apps url
    path('captcha/', include('captcha.urls')),
]

urlpatterns += app_view_patterns
urlpatterns += js_i18n_patterns

if settings.DEBUG:
    urlpatterns += [
        re_path('swagger(?P<format>.json|.yaml)',
                get_swagger_view().without_ui(cache_timeout=1), name='schema-json'),
        path('docs/', get_swagger_view().with_ui('swagger', cache_timeout=1), name="docs"),
        # path('redoc/', get_swagger_view().with_ui('redoc', cache_timeout=1), name='redoc'),
    ]

apps/assets/models/asset.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: asset.py
@ide: PyCharm
@time: 2020/5/7 11:24
@desc:
"""
import uuid
import logging
from collections import OrderedDict
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .utils import Connectivity
from organization.mixins.models import OrgModelMixin, OrgManager

__all__ = ['Asset', 'ProtocolsMixin']

logger = logging.getLogger(__name__)


class AssetQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def valid(self):
        return self.active()

    def has_protocol(self, name):
        return self.filter(protocols__contains=name)


class ProtocolsMixin:
    protocols = ''
    PROTOCOL_SSH = 'ssh'
    PROTOCOL_RDP = 'rdp'
    PROTOCOL_TELNET = 'telnet'
    PROTOCOL_VNC = 'vnc'
    PROTOCOL_CHOICES = (
        (PROTOCOL_SSH, 'ssh'),
        (PROTOCOL_RDP, 'rdp'),
        (PROTOCOL_TELNET, 'telnet'),
        (PROTOCOL_VNC, 'vnc'),
    )

    @property
    def protocols_as_list(self):
        if not self.protocols:
            return []
        return self.protocols.split(' ')

    @property
    def protocols_as_dict(self):
        d = OrderedDict()
        protocols = self.protocols_as_list
        for i in protocols:
            if '/' not in i:
                continue
            name, port = i.split('/')[:2]
            if not all([name, port]):
                continue
            d[name] = int(port)
        return d

    @property
    def protocols_as_json(self):
        return [
            {"name": name, "port": port}
            for name, port in self.protocols_as_dict.items()
        ]

    def has_protocol(self, name):
        return name in self.protocols_as_dict

    @property
    def ssh_port(self):
        return self.protocols_as_dict.get("ssh", 22)


class Asset(ProtocolsMixin, OrgModelMixin):
    # Important
    PLATFORM_CHOICES = (
        ('Linux', 'Linux'),
        ('Unix', 'Unix'),
        ('MacOS', 'MacOS'),
        ('BSD', 'BSD'),
        ('Windows', 'Windows'),
        ('Windows2012', 'Windows(2012)'),
        ('Windows2016', 'Windows(2016)'),
        ('Windows2019', 'Windows(2019)'),
        ('Other', 'Other'),
    )

    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    ip = models.CharField(
        max_length=128, verbose_name=_('IP'), db_index=True
    )
    instance_id = models.CharField(
        blank=True, null=True,
        max_length=128, verbose_name=_('Instance ID')
    )
    instance_type = models.CharField(
        blank=True, null=True,
        max_length=128, verbose_name=_('Instance Type')
    )
    instance_state = models.CharField(
        blank=True, null=True,
        max_length=128, verbose_name=_('Instance State')
    )
    hostname = models.CharField(
        max_length=128, verbose_name=_('Hostname')
    )
    protocol = models.CharField(
        max_length=128, default=ProtocolsMixin.PROTOCOL_SSH,
        choices=ProtocolsMixin.PROTOCOL_CHOICES, verbose_name=_('Protocol')
    )
    platform = models.CharField(
        max_length=128, choices=PLATFORM_CHOICES,
        default='Linux', verbose_name=_('Platform')
    )
    port = models.IntegerField(default=22, verbose_name=_('Port'))
    public_ip = models.CharField(
        blank=True, null=True,
        max_length=128, verbose_name=_('Public IP'), db_index=True
    )
    private_ip = models.CharField(
        blank=True, null=True,
        max_length=128, verbose_name=_('Private IP'), db_index=True
    )
    is_active = models.BooleanField(
        default=True, verbose_name=_('Is active')
    )
    region = models.ForeignKey(
        'assets.region', on_delete=models.PROTECT, null=True,
        related_name='assets_region', verbose_name=_("Region")
    )
    # Auth
    admin_user = models.ForeignKey(
        'assets.AdminUser', on_delete=models.PROTECT, null=True,
        verbose_name=_("Admin user"), related_name='assets'
    )
    sn = models.CharField(
        max_length=128, null=True,
        blank=True, verbose_name=_('Serial number')
    )
    cpu_model = models.CharField(
        max_length=64, null=True, blank=True, verbose_name=_('CPU model')
    )
    cpu_count = models.IntegerField(
        null=True, verbose_name=_('CPU count')
    )
    cpu_cores = models.IntegerField(
        null=True, verbose_name=_('CPU cores')
    )
    cpu_vcpus = models.IntegerField(
        null=True, verbose_name=_('CPU vcpus')
    )
    memory = models.CharField(
        max_length=64, null=True, blank=True, verbose_name=_('Memory')
    )
    disk_total = models.CharField(
        max_length=1024, null=True, blank=True, verbose_name=_('Disk total')
    )
    disk_info = models.CharField(
        max_length=1024, null=True, blank=True, verbose_name=_('Disk info')
    )
    os = models.CharField(
        max_length=128, null=True, blank=True, verbose_name=_('OS')
    )
    os_version = models.CharField(
        max_length=16, null=True, blank=True, verbose_name=_('OS version')
    )
    os_arch = models.CharField(
        max_length=16, blank=True, null=True, verbose_name=_('OS arch')
    )
    hostname_raw = models.CharField(
        max_length=128, blank=True, null=True, verbose_name=_('Hostname raw')
    )
    tags = models.ManyToManyField(
        'assets.Tags', blank=True,
        related_name='assets', verbose_name=_("Tags")
    )
    created_by = models.CharField(
        max_length=32, null=True,
        blank=True, verbose_name=_('Created by')
    )
    date_created = models.DateTimeField(
        auto_now_add=True, null=True,
        blank=True, verbose_name=_('Date created')
    )
    comment = models.TextField(
        max_length=128, default='',
        blank=True, verbose_name=_('Comment')
    )

    objects = OrgManager.from_queryset(AssetQuerySet)()
    _connectivity = None

    def __str__(self):
        return '{0.hostname}({0.ip})'.format(self)

    @property
    def is_valid(self):
        warning = ''
        if not self.is_active:
            warning += ' inactive'
        if warning:
            return False, warning
        return True, warning

    def is_windows(self):
        if self.platform in ("Windows", "Windows2012", "Windows2016", "Windows2019"):
            return True
        else:
            return False

    def is_unix_like(self):
        if self.platform not in ("Windows", "Windows2012", "Windows2016", "Windows2019", "Other"):
            return True
        else:
            return False

    def is_support_ansible(self):
        return self.has_protocol('ssh') and self.platform not in ("Other",)

    @property
    def cpu_info(self):
        info = ""
        if self.cpu_model:
            info += self.cpu_model
        if self.cpu_count and self.cpu_cores:
            info += "{}*{}".format(self.cpu_count, self.cpu_cores)
        return info

    @property
    def hardware_info(self):
        if self.cpu_count:
            return '{} Core {} {}'.format(
                self.cpu_vcpus or self.cpu_count * self.cpu_cores,
                self.memory, self.disk_total
            )
        else:
            return ''

    @property
    def connectivity(self):
        if self._connectivity:
            return self._connectivity
        if not self.admin_user:
            return Connectivity.unknown()
        connectivity = self.admin_user.get_asset_connectivity(self)
        return connectivity

    @connectivity.setter
    def connectivity(self, value):
        if not self.admin_user:
            return
        self.admin_user.set_asset_connectivity(self, value)

    def get_auth_info(self):
        if not self.admin_user:
            return {}

        self.admin_user.load_specific_asset_auth(self)
        info = {
            'username': self.admin_user.username,
            'password': self.admin_user.password,
            'private_key': self.admin_user.private_key_file,
        }
        return info

    class Meta:
        unique_together = [('org_id', 'hostname')]
        verbose_name = _("Asset")

apps/assets/forms/user.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: user.py
@ide: PyCharm
@time: 2020/5/8 17:08
@desc:
"""
from django import forms
from django.utils.translation import gettext_lazy as _

from common.utils import validate_ssh_private_key, ssh_pubkey_gen, get_logger
from organization.mixins.forms import OrgModelForm
from ..models import AdminUser, SystemUser
from ..const import GENERAL_FORBIDDEN_SPECIAL_CHARACTERS_HELP_TEXT

logger = get_logger(__file__)
__all__ = [
    'FileForm', 'SystemUserForm', 'AdminUserForm', 'PasswordAndKeyAuthForm',
]


class FileForm(forms.Form):
    file = forms.FileField()


class PasswordAndKeyAuthForm(forms.ModelForm):
    # Form field name can not start with `_`, so redefine it,
    password = forms.CharField(
        widget=forms.PasswordInput, max_length=128,
        strip=True, required=False,
        help_text=_('Password or private key passphrase'),
        label=_("Password"),
    )
    # Need use upload private key file except paste private key content
    private_key = forms.FileField(required=False, label=_("Private key"))

    def clean_private_key(self):
        private_key_f = self.cleaned_data['private_key']
        password = self.cleaned_data['password']

        if private_key_f:
            key_string = private_key_f.read()
            private_key_f.seek(0)
            key_string = key_string.decode()

            if not validate_ssh_private_key(key_string, password):
                msg = _('Invalid private key, Only support '
                        'RSA/DSA format key')
                raise forms.ValidationError(msg)
        return private_key_f

    def validate_password_key(self):
        password = self.cleaned_data['password']
        private_key_f = self.cleaned_data.get('private_key', '')

        if not password and not private_key_f:
            raise forms.ValidationError(_(
                'Password and private key file must be input one'
            ))

    def gen_keys(self):
        password = self.cleaned_data.get('password', '') or None
        private_key_f = self.cleaned_data['private_key']
        public_key = private_key = None

        if private_key_f:
            private_key = private_key_f.read().strip().decode('utf-8')
            public_key = ssh_pubkey_gen(private_key=private_key, password=password)
        return private_key, public_key


class AdminUserForm(PasswordAndKeyAuthForm):
    # def save(self, commit=True):
    #     raise forms.ValidationError("Use api to save")

    class Meta:
        model = AdminUser
        fields = ['name', 'username', 'password', 'private_key', 'comment']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Name')}),
            'username': forms.TextInput(attrs={'placeholder': _('Username')}),
        }


class SystemUserForm(OrgModelForm, PasswordAndKeyAuthForm):
    # Admin user assets define, let user select, save it in form not in view
    auto_generate_key = forms.BooleanField(initial=True, required=False)

    def save(self, commit=True):
        raise forms.ValidationError("Use api to save")

    class Meta:
        model = SystemUser
        fields = [
            'name', 'username', 'protocol', 'auto_generate_key',
            'password', 'private_key', 'auto_push', 'sudo',
            'comment', 'shell', 'priority', 'login_mode', 'cmd_filters',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': _('Name')}),
            'username': forms.TextInput(attrs={'placeholder': _('Username')}),
            'cmd_filters': forms.SelectMultiple(attrs={
                'class': 'select2', 'data-placeholder': _('Command filter')
            }),
        }
        help_texts = {
            'name': GENERAL_FORBIDDEN_SPECIAL_CHARACTERS_HELP_TEXT,
            'auto_push': _('Auto push system user to asset'),
            'priority': _('1-100, High level will be using login asset as default, '
                          'if user was granted more than 2 system user'),
            'login_mode': _('If you choose manual login mode, you do not '
                            'need to fill in the username and password.'),
            'sudo': _("Use comma split multi command, ex: /bin/whoami,/bin/ifconfig")
        }

apps/assets/views.py
from django.shortcuts import render

# Create your views here.

apps/assets/views/region.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: sun
@license: (C) Copyright 2016-2019, Light2Cloud (Beijing) Web Service Co., LTD
@contact: wenhaijie@light2cloud.com
@software: L2CloudCMP
@file: region.py
@ide: PyCharm
@time: 2021/2/27 12:31
@desc:
"""
from django.views.generic import TemplateView, CreateView, \
    UpdateView
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse_lazy

from common.permissions import PermissionsMixin, IsOrgAdmin
from common.const import create_success_msg, update_success_msg
from ..models import Region
from ..forms import RegionForm


class RegionListView(PermissionsMixin, TemplateView):
    template_name = 'assets/region_list.html'
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Assets'),
            'action': _('Region list'),
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class RegionCreateView(PermissionsMixin, CreateView):
    model = Region
    template_name = 'assets/region_create_update.html'
    form_class = RegionForm
    success_url = reverse_lazy('assets:region-list')
    success_message = create_success_msg
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Assets'),
            'action': _('Create region'),
            'type': 'create'
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)


class RegionUpdateView(PermissionsMixin, UpdateView):
    model = Region
    template_name = 'assets/region_create_update.html'
    form_class = RegionForm
    success_url = reverse_lazy('assets:region-list')
    success_message = update_success_msg
    permission_classes = [IsOrgAdmin]

    def get_context_data(self, **kwargs):
        context = {
            'app': _('Assets'),
            'action': _('Update region'),
            'type': 'update'
        }
        kwargs.update(context)
        return super().get_context_data(**kwargs)

apps/assets/templates/assets/_asset_import_modal.html
{% extends '_import_modal.html' %}
{% load i18n %}

{% block modal_class %}modal-lg{% endblock %}

{% block modal_title%}{% trans "Import assets" %}{% endblock %}

{% block import_modal_download_template_url %}{% url "api-assets:asset-list" %}{% endblock %}

apps/assets/templates/assets/_asset_region_create_model.html
{% extends '_modal.html' %}
{% load i18n %}
{% load static %}

{% block modal_id %}create_modal{% endblock %}

{% block modal_class %}modal-lg{% endblock %}

{% block modal_confirm_id %}btn_create_confirm{% endblock %}

{% block modal_title%}{% trans "Create region" %}{% endblock %}

{% block modal_body %}
    <form class="form-horizontal form-material" method="post" id="fm_create">
        <div class="form-group">
            <div class="col-md-12 m-b-20">
                <input type="text" class="form-control" name="name" placeholder="{% trans 'name' %}">
            </div>
            <div class="col-md-12 m-b-20">
                <input type="text" class="form-control" name="owner" placeholder="{% trans 'owner' %}">
            </div>
            <div class="col-md-12 m-b-20">
                <input type="text" class="form-control" name="telephone" placeholder="{% trans 'telephone' %}">
            </div>
            <div class="col-md-12 m-b-20">
                <input type="text" class="form-control" name="address" placeholder="{% trans 'address' %}">
            </div>
            <div class="col-md-12 m-b-20">
                <textarea class="form-control" rows="5" name="comment" placeholder="{% trans 'comment' %}"></textarea>
            </div>
        </div>
    </form>
{% endblock %}

apps/assets/templates/assets/_system_user.html
{% extends '_base_create_update.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}

{% block bread_crumbs %}
    <li class="breadcrumb-item">
        <a href="{% url 'assets:system-user-list' %}">{% trans "System user list" %}</a>
    </li>
    <li class="breadcrumb-item active">{% trans action %}</li>
{% endblock %}

{% block form %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <form method="post" class="form-horizontal" action="" enctype="multipart/form-data">{% csrf_token %}

        <div class="form-group">
            <h3 class="box-title">{% trans 'Basic' %}</h3>
            <hr class="m-t-0 m-b-40">
            {% bootstrap_field form.name layout="horizontal" %}
            {% bootstrap_field form.login_mode layout="horizontal" %}
            {% bootstrap_field form.username layout="horizontal" %}
            {% bootstrap_field form.priority layout="horizontal" %}
            {% bootstrap_field form.protocol layout="horizontal" %}

            <h3 class="box-title" id="auth_title_id">{% trans 'Auth' %}</h3>
            <hr class="m-t-0 m-b-40">
            {% block auth %}
                <div class="form-group row">
                    <label class="col-md-3 col-form-label" for="id_protocol">{% trans 'Auto generate key' %}</label>
                    <div class="col-md-9">
                        {{ form.auto_generate_key }}
                        <label for="{{ form.auto_generate_key.id_for_label }}"></label>
                    </div>
                </div>

                <div class="auth-fields">
                    {% bootstrap_field form.password layout="horizontal" %}
                    {% bootstrap_field form.private_key layout="horizontal" %}
                </div>
                <div class="form-group row">
                    <label for="{{ form.auto_push.id_for_label }}" class="col-md-3 col-form-label">{% trans 'Auto push' %}</label>
                    <div class="col-sm-9">
                        {{ form.auto_push }}
                        <label for="{{ form.auto_push.id_for_label }}"></label>
                    </div>
                </div>
            {% endblock %}

            <div id="command-filter-block">
                <h3 class="box-title">{% trans 'Command filter' %}</h3>
                <hr class="m-t-0 m-b-40">
                {% bootstrap_field form.cmd_filters layout="horizontal" %}
            </div>

            <h3 class="box-title">{% trans 'Other' %}</h3>
            <hr class="m-t-0 m-b-40">
            {% bootstrap_field form.sudo layout="horizontal" %}
            {% bootstrap_field form.shell layout="horizontal" %}
            {% bootstrap_field form.comment layout="horizontal" %}
        </div>
        <hr>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn btn-outline-success">{% trans 'Submit' %}</button>
                            <button type="reset" class="btn btn-outline-warning">{% trans 'Reset' %}</button>
                            <a href="{% url 'assets:system-user-list' %}" class="btn btn-outline-info">{% trans 'Cancel' %}</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </div>
    </form>
{% endblock %}

{#{% block custom_head_css_js %}#}
{#    <style>#}
{#        .form-group.required .control-label:after {#}
{#            color: #d00;#}
{#            content: "*";#}
{#            position: absolute;#}
{#            margin-left: 8px;#}
{#            top: 7px;#}
{#        }#}
{#    </style>#}
{#{% endblock %}#}
{% block custom_foot_js %}
    <script>
        let protocol_id = '#' + '{{ form.protocol.id_for_label }}';
        let login_mode_id = '#' + '{{ form.login_mode.id_for_label }}';
        let auto_generate_key = '#' + '{{ form.auto_generate_key.id_for_label }}';
        let password_id = '#' + '{{ form.password.id_for_label }}';
        let private_key_id = '#' + '{{ form.private_key.id_for_label }}';
        let auto_push_id = '#' + '{{ form.auto_push.id_for_label }}';
        let sudo_id = '#' + '{{ form.sudo.id_for_label }}';
        let shell_id = '#' + '{{ form.shell.id_for_label }}';

        function autoLoginModeProtocol() {
            // 协议+自动登录模式字段控制
            $('#auth_title_id').removeClass('d-none');
            let protocol = $(protocol_id + " option:selected").text();
            if (protocol === 'rdp') {
                authFieldsDisplay();
                $(auto_generate_key).closest('.form-group').removeClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').removeClass('d-none');
                $(auto_push_id).closest('.form-group').removeClass('d-none');
                $('#command-filter-block').addClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else if (protocol === 'vnc') {
                $('.auth-fields').removeClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').removeClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').addClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else if (protocol === 'telnet') {
                $('.auth-fields').removeClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').removeClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').removeClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else {
                authFieldsDisplay();
                $(auto_generate_key).closest('.form-group').removeClass('d-none');
                $(private_key_id).closest('.form-group').removeClass('d-none');
                $(password_id).closest('.form-group').removeClass('d-none');
                $(auto_push_id).closest('.form-group').removeClass('d-none');
                $('#command-filter-block').removeClass('d-none');
                $(sudo_id).closest('.form-group').removeClass('d-none');
                $(shell_id).closest('.form-group').removeClass('d-none');
            }
        }

        function manualLoginModeProtocol() {
            // 协议+手动登录模式字段控制
            $('#auth_title_id').addClass('d-none');
            let protocol = $(protocol_id + " option:selected").text();
            if (protocol === 'rdp') {
                $('.auth-fields').addClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').addClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else if (protocol === 'vnc') {
                $('.auth-fields').addClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').addClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else if (protocol === 'telnet') {
                $('.auth-fields').addClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').removeClass('d-none');
                $(sudo_id).closest('.form-group').addClass('d-none');
                $(shell_id).closest('.form-group').addClass('d-none');
            } else {
                $('.auth-fields').addClass('d-none');
                $(auto_generate_key).closest('.form-group').addClass('d-none');
                $(password_id).closest('.form-group').addClass('d-none');
                $(private_key_id).closest('.form-group').addClass('d-none');
                $(auto_push_id).closest('.form-group').addClass('d-none');
                $('#command-filter-block').removeClass('d-none');
                $(sudo_id).closest('.form-group').removeClass('d-none');
                $(shell_id).closest('.form-group').removeClass('d-none');
            }

        }

        function authFieldsDisplay() {
            if ($(auto_generate_key).prop('checked')) {
                $('.auth-fields').addClass('d-none');
            } else {
                $('.auth-fields').removeClass('d-none');
            }
        }

        function fieldDisplay() {
            let login_mode = $(login_mode_id).val();
            if (login_mode === 'manual') {
                manualLoginModeProtocol();
            } else if (login_mode === 'auto') {
                autoLoginModeProtocol();
            }
        }

        $(document).ready(function () {
            $('.select2').select2();
            authFieldsDisplay();
            fieldDisplay();
        })
            .on('change', auto_generate_key, function () {
                authFieldsDisplay();
            })
            .on('change', login_mode_id, function () {
                fieldDisplay();
            })
            .on('change', protocol_id, function () {
                fieldDisplay();
            }).on("submit", "form", function (evt) {
            evt.preventDefault();
            {% block formUrl %}
                let the_url = '{% url 'api-assets:system-user-list' %}';
                let redirect_to = '{% url "assets:system-user-list" %}';
                let method = "POST";
            {% endblock %}
            let form = $("form");
            let data = form.serializeObject();

            objectAttrsIsList(data, ['cmd_filters']);
            objectAttrsIsBool(data, ["auto_generate_key", "auto_push"]);
            data["private_key"] = $("#id_private_key").data('file');

            let props = {
                url: the_url,
                data: data,
                method: method,
                form: form,
                redirect_to: redirect_to
            };
            formSubmit(props);
        }).on('change', '#id_private_key', function () {
            readFile($(this)).on("onload", function (evt, data) {
                $(this).data("file", data)
            })
        })

    </script>
{% endblock %}

apps/assets/templates/assets/asset_update.html
{% extends 'assets/asset_create.html' %}
{% load bootstrap4 %}
{% load i18n %}


{% block formUrl %}
    var the_url = '{% url 'api-assets:asset-detail' pk=object.id %}';
    var redirect_to = '{% url "assets:asset-list" %}';
    var method = 'PUT';
{% endblock %}

apps/assets/templates/assets/system_user_create.html
{% extends 'assets/_system_user.html' %}

{% block auth %}
    {{ block.super }}
{% endblock %}